# Generated by Django 4.2.5 on 2023-10-02 07:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_group_chat', models.BooleanField(default=False)),
                ('participants', models.ManyToManyField(related_name='chat', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestampe', models.DateTimeField()),
                ('has_replay', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('SEEN', 'Seen')], default='PENDING', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('replay_to_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.message')),
                ('media_file', models.FileField(upload_to='media_messages')),
            ],
            bases=('chat.message',),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile_pictures')),
                ('picture_blurhash', models.CharField(blank=True, max_length=200, null=True)),
                ('default_avatar', models.CharField(blank=True, choices=[('images/avatar/default_avatar_1.png', 'default'), ('images/avatar/1.png', '1'), ('images/avatar/2.png', '2'), ('images/avatar/3.png', '3'), ('images/avatar/4.png', '4'), ('images/avatar/5.png', '5'), ('images/avatar/6.png', '6'), ('images/avatar/7.png', '7'), ('images/avatar/8.png', '8'), ('images/avatar/9.png', '9')], default='images/avatar/default_avatar_1.png', null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], default='OFFLINE')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='Text')),
                ('timestamp', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_activity_type', models.CharField(choices=[('MESSAGE', 'Message'), ('IMAGE', 'Image'), ('AUDIO', 'Audio'), ('CALL', 'Call'), ('NEW', 'New')], default='New')),
                ('last_activity', models.CharField(blank=True, max_length=200, null=True)),
                ('last_activity_time', models.DateTimeField(null=True)),
                ('unread_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
