# Generated by Django 4.2.4 on 2023-09-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='profile',
        ),
    ]
