# Generated by Django 4.2.4 on 2023-09-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_contacts_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture_blurhash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
