# Generated by Django 4.2.4 on 2023-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_picture_blurhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('IMAGE', 'Image')], default='Text'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
